name: Quark Sign-in

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间 1:00 执行，即北京时间 9:00

  workflow_dispatch:  # 手动触发

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Quark Sign-in
        env:
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
        run: |
          python checkIn_Quark.py
          
      - name: Send output to WeChat via PushPlus
        if: always()  # 无论任务成功或失败都发送消息
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          OUTPUT="${{ steps.run-script.outputs.output }}"
          curl -X POST "https://www.pushplus.plus/send" \
            -H "Content-Type: application/json" \
            -d '{
              "token": "'"$PUSHPLUS_TOKEN"'",
              "title": "夸克签到结果",
              "content": "'"$OUTPUT"'"
            }'
